name: Calculadora Workflow

on:
  push:
    branches:
      - main

jobs:
    calculadora_job:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11.9'

        - name: Install dependencies
          run: pip install -r requirements.txt
        
        - name: Run tests
          run: pytest -v
